version: "3.9"

services:

  frontend:
    build: frontend
    # 8000 er porten med incoming traffic, trafikken bliver sendt hen på 8080
    ports: 
      - 8000:8080

    # envoirment info om backend, så den kan forbinde
    environment:
      BACKEND_DNS: backend
      BACKEND_PORT: 9000

  backend:
    build: backend
    expose: 
      - 9000
