name: test
on: push

jobs:

  Clone-down:
    name: Clone down repo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload Repo
      uses: actions/upload-artifact@v2
      with:
        name: code
        path: .

  test:
    name: testing
    needs: Clone-down
    steps:
    - name: download code 
      uses: actions/download-artifact@v2
      with:
        name: code
        path: .
    
    - name: run test
      run: go test frontend/main_test.go