name: test
on: push

jobs:
  Test:

    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15

      - name: Test
        run: cd frontend && go test