name: test
on: push

env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
  REPO_NAME: ${{ secrets.REPO_NAME }}
  REPO_NAME_BACKEND: ${{ secrets.REPO_NAME_BACKEND }} 

jobs:
  Test:

    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15

      - name: Test
        run: cd frontend && go test

  Docker-image:
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
      - name: login docker
        run: |
          docker login -u ${{env.docker_username}} -p ${{env.docker_password}}

      - name: Date 
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"

      - name: build frontend
        run: cd .. && cd frontend && docker build . --file Dockerfile --tag $REPO_NAME:${{ steps.date.outputs.date }} && cd ..

      - name: Docker push
        run: docker push $REPO_NAME:${{ steps.date.outputs.date }}

      - name: build backend
        run: cd backend && docker build . --file Dockerfile --tag $REPO_NAME_BACKEND:${{ steps.date.outputs.date }}
      
      - name: Docker push
        run: docker push $REPO_NAME_BACKEND:${{ steps.date.outputs.date }}


