name: test
on: push

jobs:
  Test:

    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15

      - name: Test
        run: cd frontend && go test

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: To Dockerhub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: owagn20/devops:latest, owagn20/devops:${{ github.run_number }}